### ISSUE TITLE
Update Release wiki

### ISSUE THREAD

**Issue by shntnu** [0x00B1/persistence#113]
@gwaygenomics Were the instructions [here](https://github.com/cytomining/cytominer-database/wiki/Release) comprehensive? If not, could you please add to it? 

Could you also please add some pointers on how to release on conda-forge? (it could be ask simple as pointing to the docs on conda-forge.org, if you think that's sufficient)

**Comment by gwaybio** [comment]
[Updated!](https://github.com/cytomining/cytominer-database/wiki/Release)

I added an additional link for PyPI and and all conda-forge instructions
