### ISSUE TITLE
Keep track of project dependencies

### ISSUE THREAD

**Issue by shntnu** [0x00B1/persistence#31]
e.g. https://gemnasium.com/wireservice/csvkit

Gemnasium parses your project's dependencies and notifies you when new versions are released or they need to be updated.

@mcquin is this useful?

**Comment by mcquin** [comment]
@shntnu I think this is an interesting idea! We could try setting it up for this repository and see if we like using it.

We can also ensure dependencies are up to date by [changing this line](https://github.com/cytomining/cytominer-database/blob/master/.travis.yml#L15) to `pip install --upgrade --editable .`. This ensure Travis will always install the latest project dependencies.

**Comment by shntnu** [comment]
As of 4a848da, the line has been changed to `pip install --upgrade --editable .`

**Comment by shntnu** [comment]
I have set up gemnasium using my GitHub account. It is free for open-source. 

![screen shot 2017-09-26 at 1 41 50 pm](https://user-images.githubusercontent.com/1210428/30875138-825a557c-a2c0-11e7-968d-0ace52a04fc9.png)

**Comment by shntnu** [comment]
@mcquin What do you think about adding this badge to README?
(networkx is a pain!)

[![Dependency Status](https://gemnasium.com/badges/github.com/cytomining/cytominer-database.svg)](https://gemnasium.com/github.com/cytomining/cytominer-database)

**Comment by mcquin** [comment]
@shntnu Great idea!
