### ISSUE TITLE
Anaconda support

### ISSUE THREAD

**Issue by mcquin** [0x00B1/persistence#37]
... would be nice :)

**Comment by mcquin** [comment]
Nearly all of `cytominer-database`'s dependencies are available as conda packages.

1. Let's generate an environment file for users who want to use Anaconda.
1. Let's also investigate creating a conda package of `cytominer-database`.

**Comment by shntnu** [comment]
I'm attaching the conda config files that were created in #43 and deleting the related unmerged branch issues/37 (these two were only relevant changes)

[appveyor.yml.txt](https://github.com/cytomining/cytominer-database/files/3392969/appveyor.yml.txt)
[environment.yml.txt](https://github.com/cytomining/cytominer-database/files/3392970/environment.yml.txt)

**Comment by gwaybio** [comment]
Tracking conda-forge/staged-recipes#8829

**Comment by gwaybio** [comment]
closed via conda-forge/staged-recipes#8829

see https://anaconda.org/conda-forge/cytominer_database

now can install with

```python
conda install -c conda-forge cytominer_database 
```
