### ISSUE TITLE
Travis should install the latest dependencies

### ISSUE THREAD

**Issue by mcquin** [0x00B1/persistence#58]
Use `pip install --upgrade --editable .[test]` to install the latest versions of dependencies on Travis.

Additionally, I'm not sure why Cython is being installed. It doesn't appear to be necessary.

**Comment by shntnu** [comment]
We don't need cython now 

We were using it in the `relational` branch

https://github.com/cytomining/cytominer-database/commit/b1a69afa2a8858574730c65ff3b76997f41a613f

But no reason to have it here. I'll comment in the PR
