### ISSUE TITLE
Error: default config file not found

### ISSUE THREAD

**Issue by cells2numbers** [0x00B1/persistence#79]
When cytominer-database is called without explicit config file 
```
cytominer-database ingest images test.sqlite
```
the error 
```
Error: Invalid value for "-c" / "--config-file": Path "/usr/local/lib/python3.6/site-packages/cytominer_database/commands/config/config_htqc.ini" does not exist.
```
is thrown. 

Installed cytominer-database
```
pip install cytominer-database==0.0.1b4
```

**Comment by mcquin** [comment]
@cells2numbers I've got a fix for you coming up in #80 :)

Additionally, the database connection string should be the full URI: `sqlite:///test.sqlite`
