### ISSUE TITLE
Optionally skip Image_ prefix

### ISSUE THREAD

**Issue by shntnu** [0x00B1/persistence#86]
It is often convenient to leave out the `Image_` prefix for names of columns in the per image table. E.g. `Metadata_Plate` instead of  `Image_Metadata_Plate`. Include this as an option.

    --skip-image-prefix / --no-skip-image-prefix  True if the prefix of image table name should be excluded from the names of columns from per image table e.g. use  `Metadata_Plate` instead of`Image_Metadata_Plate`.

**Comment by mcquin** [comment]
Resolved #87
